name: Generate Changelog

on:
  release:
    types:
      - created
      - published

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install standard-version
        run: npm install --save-dev standard-version

      - name: Generate changelog
        run: |
          npx standard-version --release-as minor  # Oder major, patch, je nach Bedarf

      - name: Commit changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog"
          git push origin HEAD:master
