name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.ts'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 --tag ghcr.io/oleeeedev/nextjs-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker images
          if [[ "$(docker images -q ghcr.io/oleeeedev/nextjs-app:${{ github.sha }})" == "" ]]; then
            echo "Image not found, aborting push."
            exit 1
          fi
          docker push ghcr.io/oleeeedev/nextjs-app:${{ github.sha }}

