name: Docker Build & Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --build-arg CACHEBUST=$(date +%s) -t ghcr.io/${{ github.repository_owner }}/nextjs-app:${{ env.VERSION }} .
          docker images  # Listet alle Bilder nach dem Build

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nextjs-app:${{ env.VERSION }}
